---
# tasks file for 2PRecuperatorio
- name: "Crear directorio /tmp/alumno"
  file:
    path: /tmp/alumno
    state: directory  
    mode: '0755'

- name: "Crear archivo de datos"
  copy:
    dest: /tmp/alumno/datos.txt
    content: |
      Nombre: Axel
      Apellido: Bañez
      División: 114
      Fecha: {{ ansible_date_time.date }}
      --------------------------------------------- 
      Distribución: {{ ansible_distribution }}
      Cantidad de Cores: {{ ansible_processor_cores }}

